GET http://localhost:3001/

### register
POST http://localhost:3004/auth/register
Content-Type: application/json

{
    "username":"email@gmail.com",
    "password":"123456"
}


### login
POST http://localhost:3004/auth/login
Content-Type: application/json

{
    "username":"email@gmail.com",
    "password":"123456"
}


### GET todos

GET http://localhost:3004/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ3NTk2MTI4LCJleHAiOjE3NDc2ODI1Mjh9.-NMnxe1D6syEhhpOUpOFIs9vKzeRRXQIhR1vs0rp7aw


### POST todos
POST http://localhost:3004/todos
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ3NTk2MTI4LCJleHAiOjE3NDc2ODI1Mjh9.-NMnxe1D6syEhhpOUpOFIs9vKzeRRXQIhR1vs0rp7aw


{
    "task": "cook"
}


### PUT todos

PUT http://localhost:3004/todos
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ3NTk2MTI4LCJleHAiOjE3NDc2ODI1Mjh9.-NMnxe1D6syEhhpOUpOFIs9vKzeRRXQIhR1vs0rp7aw


{
    "task": "code",
    "completed":1
}