GET http://localhost:3001/

###
POST http://localhost:3004/auth/register
Content-Type: application/json

{
    "username":"email@gmail.com",
    "password":"123456"
}


###
POST http://localhost:3004/auth/login
Content-Type: application/json

{
    "username":"email@gmail.com",
    "password":"123456"
}


### GET todos

GET http://localhost:3004/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ3NTkzNzA1LCJleHAiOjE3NDc2ODAxMDV9.lqeTYnI-9q8naTilmI4IqgZr7aUI_rIDE-yzO4A38h4
### POST todos
POST http://localhost:3004/todos
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ3NTkzNzA1LCJleHAiOjE3NDc2ODAxMDV9.lqeTYnI-9q8naTilmI4IqgZr7aUI_rIDE-yzO4A38h4

{
    "task": "cook"
}


