GET http://localhost:3001/

### register
POST http://localhost:3004/auth/register
Content-Type: application/json

{
    "username":"email@gmail.com",
    "password":"123456"
}


### login
POST http://localhost:3004/auth/login
Content-Type: application/json

{
    "username":"email@gmail.com",
    "password":"123456"
}


### GET todos

GET http://localhost:3004/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ3NTk3MzM3LCJleHAiOjE3NDc2ODM3Mzd9.S_TUvDt-XGUs1B1GWJz6hbjUVS5MgQ6jnCc_AtfmcTs

### POST todos
POST http://localhost:3004/todos
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ3NTk3MzM3LCJleHAiOjE3NDc2ODM3Mzd9.S_TUvDt-XGUs1B1GWJz6hbjUVS5MgQ6jnCc_AtfmcTs

{
    "task": "cook 4"
}


### PUT todos

PUT http://localhost:3004/todos/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ3NTk3MzM3LCJleHAiOjE3NDc2ODM3Mzd9.S_TUvDt-XGUs1B1GWJz6hbjUVS5MgQ6jnCc_AtfmcTs

{
    "completed":1
}