### TEST GET /

GET http://localhost:3000

### TEST GET /home

GET http://localhost:3000/display


### TEST POST /api/data

POST http://localhost:3000/api/data
Content-Type: application/json

{
    "name" : "mpolo3"
}

### TEST POST /api/data

DELETE http://localhost:3000/api/delete
Content-Type: application/json

{
    "name" : "mpolo2"
}