version: 3

services:
  app:
    build:
    container_name: todoapp
    environment:
      -DATABASE_URL==postgresql://myuser:mysecretpassword@db:5432/todoapp
      -JWT_SECRET=secret_jwt
      -NODE_ENV=development
      -PORT=3005
    port:
      -"3005:3005"
    depends_on:
      -db
    volumes:
    - .:/app
  db:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes: 
  postgres-data:
